[package]
name = "ls-enhanced"
description = "a better looking ls command"
version = "0.1.4"
edition = "2021"
license = "MIT"

[dependencies]
colored = "2.1.0"
toml = "0.8.19"
serde = "1.0.207"
serde_derive = "1.0.207"
term_size = "0.3.2"
